# Generated by Django 5.1.2 on 2024-10-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps1', '0004_parent1_parent2_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=64)),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField(max_length=256)),
            ],
        ),
    ]
